In [1]:
import numpy as np
from coffea.util import load

In [2]:
filename = "/work/mmarcheg/BTVNanoCommissioning/histograms/test_projmass_v07.coffea"
output = load(filename)

In [3]:
h_pt = output['fatjet_pt']
h_pt

<Hist (dataset,region,flavor,pt) instance at 0x7fbba979db80>

In [4]:
datasets_qcd = [str(s) for s in h_pt.identifiers('dataset') if 'QCD' in str(s)]
datasets_qcd

['QCD_Pt-1000toInf_MuEnrichedPt5_TuneCP5_13TeV_pythia8',
 'QCD_Pt-120to170_MuEnrichedPt5_TuneCP5_13TeV_pythia8',
 'QCD_Pt-170to300_MuEnrichedPt5_TuneCP5_13TeV_pythia8',
 'QCD_Pt-300to470_MuEnrichedPt5_TuneCP5_13TeV_pythia8',
 'QCD_Pt-470to600_MuEnrichedPt5_TuneCP5_13TeV_pythia8',
 'QCD_Pt-600to800_MuEnrichedPt5_TuneCP5_13TeV_pythia8',
 'QCD_Pt-800to1000_MuEnrichedPt5_TuneCP5_13TeV_pythia8']

In [5]:
datasets_data = [str(s) for s in h_pt.identifiers('dataset') if 'BTagMu' in str(s)]
datasets_data

['BTagMuA', 'BTagMuB', 'BTagMuC', 'BTagMuD']

In [6]:
h_data = h_pt[datasets_data].sum('dataset')['basic'].sum('region', 'flavor')
h_mc   = h_pt[datasets_qcd].sum('dataset')['basic'].sum('region', 'flavor')
h_data

<Hist (pt) instance at 0x7fbba9d068b0>

In [7]:
n_data = h_data.values()[()]
n_mc   = h_mc.values()[()]
n_data

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0., 556., 513., 532., 487., 463., 424., 432.,
       428., 420., 403., 365., 338., 344., 293., 302., 265., 259., 227.,
       236., 198., 191., 199., 159., 161., 139., 163., 159., 141., 148.,
       120., 137., 111.,  92.,  99., 113., 105.,  94.,  79.,  74.,  72.,
        76.,  74.,  75.,  56.,  73.,  59.,  47.,  59.,  53.,  54.,  51.,
        43.,  37.,  41.,  46.,  41.,  37.,  23.,  32.,  36.,  24.,  25.,
        28.,  17.,  12.,  14.,  24.,  22.,  15.,  19.,  23.,  15.,  17.,
        14.,  25.,  18.,  15.,  15.,  10.,   8.,  1

In [20]:
mod_rat = np.nan_to_num(n_data/n_mc)
mod_rat

/tmp/ipykernel_72058/1832400644.py:1: RuntimeWarning: invalid value encountered in true_divide
  mod_rat = np.nan_to_num(n_data/n_mc)


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.06313092, 0.05896142, 0.06201299, 0.0576253 , 0.05623

In [26]:
edges = h_pt.axes()[-1].edges()
edges

array([   0.,    5.,   10.,   15.,   20.,   25.,   30.,   35.,   40.,
         45.,   50.,   55.,   60.,   65.,   70.,   75.,   80.,   85.,
         90.,   95.,  100.,  105.,  110.,  115.,  120.,  125.,  130.,
        135.,  140.,  145.,  150.,  155.,  160.,  165.,  170.,  175.,
        180.,  185.,  190.,  195.,  200.,  205.,  210.,  215.,  220.,
        225.,  230.,  235.,  240.,  245.,  250.,  255.,  260.,  265.,
        270.,  275.,  280.,  285.,  290.,  295.,  300.,  305.,  310.,
        315.,  320.,  325.,  330.,  335.,  340.,  345.,  350.,  355.,
        360.,  365.,  370.,  375.,  380.,  385.,  390.,  395.,  400.,
        405.,  410.,  415.,  420.,  425.,  430.,  435.,  440.,  445.,
        450.,  455.,  460.,  465.,  470.,  475.,  480.,  485.,  490.,
        495.,  500.,  505.,  510.,  515.,  520.,  525.,  530.,  535.,
        540.,  545.,  550.,  555.,  560.,  565.,  570.,  575.,  580.,
        585.,  590.,  595.,  600.,  605.,  610.,  615.,  620.,  625.,
        630.,  635.,

In [23]:
mod_rat[edges[:-1] < 350] = 1
mod_rat

array([1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
      

In [24]:
mod_rat[edges[:-1] > 1500] = 1
mod_rat

array([1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
      